version: '2'
services:
  sql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reports
    networks:
      - infoshare_network
  jboss:
    build: ./jboss
    ports:
      - 18080:8080
      - 19990:9990
      - 15005:5005
    volumes:
      - ../target/report-module.war:/opt/jboss/wildfly/standalone/deployments/report-module.war
    networks:
      - infoshare_network
networks:
  infoshare_network:
    driver: bridge

